### ISSUE TITLE
1.20 Support?

### ISSUE THREAD

**Issue by FumpleWumper** [cleannrooster/Spellblade-Next#14]
Me and my friends play with Wizards and Paladins too, so we're just missing this mod!

Hope to see it updated soon, the mod is so well made :)

**Comment by cleannrooster** [comment]
The mod has a lot of nasty code and stuff that I'm meaning to tackle over the course of the next month or so, but that means reprogramming everything from the bottom up to be at least halfway legible lol

That means within the next few weeks I'll probably have basic spellblades, claymores, and orbs available for 1.20.1, but it might be a while before the hexblade part gets added because that's particularly where the nasty code is. Also, the hexblade module will probably be its own separate mod so players and modpacks have more control over that content. 

Stay tuned!

**Comment by cleannrooster** [comment]
Take a look at my newest mod, Invocations, as well, as that is a little side project I've been working on while procrastinating on Spellblades :P

**Comment by FumpleWumper** [comment]
Oh thank you for letting me know :0
It looks sick and I've been craving for more powerful spells! I'll also be entertaining myself with it while I wait for Spellblades :]
